/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mySidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
  */
  mySidebar: [
    {
      type: 'doc',
      id: 'greeting',
      label: '시작하기',
    },
    {
      type: 'doc',
      id: 'intro',
      label: 'Tuturial - Intro',
    },
    {
      type: 'category',
      label: 'Tutorial - Basics',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'tutorial-basics/tutorial-index' },
      // link: {
      //   type: 'generated-index',
      //   title: 'Tutorial - Basics',
      //   description: '5 minutes to learn the most important Docusaurus concepts.',
      //   slug: '/tutorial-basics',
      //   keywords: ['Tutorial'],
      //   image: '/img/docusaurus.png',
      // },
      items: [
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-page',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/markdown-features',
        'tutorial-basics/deploy-your-site',
        'tutorial-basics/congratulations',
        'tutorial-basics/test',
      ]
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      collapsible: true,
      collapsed: true,
      items: [
        'tutorial-extras/translate-your-site',
        'tutorial-extras/manage-docs-versions',
      ]
    },
    {
      type: 'link',
      label: 'My Site',
      href: 'https://www.notion.so/asttcs'
    },
  ],
  // apiSidebar: [ 'tutorial-basics/create-a-page', 'tutorial-basics/markdown-features' ]
};

module.exports = sidebars;
